pdns:
  build: .
  #image: secns/pdns
  links:
  - "mysql:db"
  ports:
  - "53:53"
  - "53:53/udp"
  - "8080:80"
  - "8001:8001"
  environment:
  - PDNS_ALLOW_AXFR_IPS=127.0.0.1
  - PDNS_DISTRIBUTOR_THREADS=3
  - PDNS_CACHE_TTL=20
  - PDNS_RECURSIVE_CACHE_TTL=10
  - PDNS_WEBSERVER=yes
  - PDNS_WEBSERVER_PASSWORD=changeme
  - PDNS_API=yes
  - PDNS_API_KEY=your_own_api_key_here
  - PDNS_API_READONLY=yes
mysql:
  image: mysql
  environment:
  - MYSQL_ROOT_PASSWORD=aPYsB84zdNZNmn64sjy
